config/routes.rb
Rails.application.routes.draw do  
  resources :animals do
    resource :rescue
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_one :rescue, dependent: :destroy
  
  def self.types
      ['Dog', 'Cat', 'Other']
  end
  
  def self.sexes
      ['Male', 'Female']
  end
  
  def self.statuses
      ['Active', 'Adopted', 'Dead']
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base    
  primary_abstract_class
end

app/models/rescue.rb
class Rescue < ApplicationRecord
  belongs_to :animal
  has_one :address, dependent: :destroy
  
  def self.organizations
      ['Laika', 'Other']
  end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
  end
  
  def show
    @animal = Animal.find(params[:id])
  end
  
  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)

    if @animal.save
      redirect_to @animal
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @animal = Animal.find(params[:id])
  end

  def update
    @animal = Animal.find(params[:id])
      
    if @animal.update(animal_params)
      redirect_to @animal
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy

    redirect_to animals_path, status: :see_other
  end

  private
    def animal_params
      params.require(:animal).permit(:name, :alias, :category, :sex, :status, :particular_signs)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rescues_controller.rb
class RescuesController < ApplicationController
  def show
    @animal = Animal.find(params[:animal_id])
  end
  
  def new
    @animal = Animal.find(params[:animal_id])
  end
  
  def create
    @animal = Animal.find(params[:animal_id])
    @animal.address = Address.new(address_params)
    @animal.build_rescue(rescue_params)
    redirect_to animal_rescue_path(@animal)
  end
  
  private
    def rescue_params
      params.require(:rescue).permit(:date, :rescuers, :organization, :notes)
    end
    
    def address_params
      params.require(:rescue).permit(:municipality, :zip_code, :neighborhood, :street)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rescues_helper.rb
module RescuesHelper
end

app/views/animals/_form.html.erb
<%= form_with model: animal do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :alias %><br>
    <%= form.text_field :alias %>
  </div>
  
  <div>
	<%= form.label :category %><br>
    <%= form.select :category, Animal.types %><br>
  </div>
  
  <div>
	<%= form.label :sex %><br>
    <%= form.select :sex, Animal.sexes %><br>
  </div>
  
  <div>
	<%= form.label :status %><br>
    <%= form.select :status, Animal.statuses %><br>
  </div>
  
  <div>
    <%= form.label :particular_signs %><br>
    <%= form.text_area :particular_signs %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Edit Animal</h1>

<%= render "form", animal: @animal %>

app/views/animals/index.html.erb
<h1>Animals</h1>

<%= link_to "New Animal", new_animal_path %>


<main>
<% @animals.each do |animal| %>
 
  <h3><%= animal.name %> (<%= animal.alias %>)</h3>
  
  <img src="https://upload.wikimedia.org/wikipedia/commons/1/18/Dog_Breeds.jpg" style="aspect-ratio:1; object-fit:cover;" />
  
  <p>
    <strong>Status:</strong>
    <%= animal.status %>
  </p>
  
  <p>
    <strong>Particular Signs:</strong>
    <%= animal.particular_signs %>
  </p>
  
  <a href="<%= animal_path(animal) %>"><button>Details</button></a>

<% end %>
</main>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render "form", animal: @animal %>

app/views/animals/show.html.erb
<h1>Animal</h1>

<nav>
	<%= link_to "Rescue", animal_rescue_path(@animal) %>
	<a href="#">Events</a>
	<a href="#">Appointments</a>
	<a href="#">Adoptions</a>
</nav>

<p>
  <strong>Name:</strong>
  <%= @animal.name %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @animal.alias %>
</p>

<p>
  <strong>Category:</strong>
  <%= @animal.category %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @animal.sex %>
</p>

<p>
  <strong>Status:</strong>
  <%= @animal.status %>
</p>

<p>
  <strong>Particular Signs:</strong>
  <%= @animal.particular_signs %>
</p>

<div>
	<a href="<%= edit_animal_path(@animal) %>"><button>Edit</button></a>
	<a href="<%= animal_path(@animal) %>" data-turbo-method="delete" data-turbo-confirm="Are you sure?"><button>Delete</button></a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Laika</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
	<link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
	
	<nav>
	  <%= link_to "Animals", animals_path %>
	</nav>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rescues/new.html.erb
<h1>New Rescue</h1>

<%= form_with url: animal_rescue_path(@animal), method: :post do |form| %>
  <div>
    <%= form.label :date %><br>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :rescuers %><br>
    <%= form.text_field :rescuers %>
  </div>
  
  <div>
	<%= form.label :organization %><br>
    <%= form.select :organization, Rescue.organizations %><br>
  </div>
  
  <div>
	<%= form.label :notes %><br>
    <%= form.text_area :notes %><br>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rescues/show.html.erb
<h1>Rescue</h1>

<%= link_to "New Rescue", new_animal_rescue_path(@animal) %>